#!/bin/sh
# 
# branch [branchname]
#
# Create a new local AND remote git branch
# Setup local branch to use remote tracking
#

branch=$1
if [ -z $branch ]; then
  echo "Usage: $0 [branchname]"
  exit 1
fi

# You were probably on master, but just in case...
old_branch=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
remote=origin

# I've run into issues using the "correct" create-remote-from-local-with-tracking flow,
# so let's just be explicit about it. Create local, push it, delete it, recreate w/ tracking

# TODO we might wanna stash & pop, or at least abort if unstashed local changes

remote_branch_exists=$(git branch -r | egrep "$remote/$branch\$")
if [ -n $remote_branch_exists ] && [ ! $remote_branch_exists == '' ]; then
  echo "* Tracking existing remote branch..."
  git checkout -b $branch --track $remote/$branch
else
  echo "* Creating new local + remote branch..."
  git checkout -b $branch
  git push $remote $branch
  git checkout $old_branch
  git branch -D $branch
  git checkout -b $branch --track $remote/$branch
fi

exit 0
