#!/bin/sh
#
# Usage: pull
#
# Pulls remote changes using rebase & tries to rebundle,
# safely stashing and re-applying your local changes, if any
#

remote="origin"
branch=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')

# Stash any local changes
stash=$(git stash)

# Update all remotes
git fetch --all || exit 1

# Pull using rebase!
git pull --rebase $remote $branch || exit 1

# Update submodules
git submodule update

# Pop any stashed changes
if [[ "$stash" =~ "No local changes to save" ]]; then
  echo "* No stashed changes, not popping"
else
  echo "* Popping stash..."
  git stash pop
fi

# Remove old, stale branches
git remote prune $remote

# Bundle em if you got em!
if which -s bundle && [ -f Gemfile ]; then
  echo "* Bundling gems..."
  bundle check >/dev/null 2>&1 || bundle install
fi

# Install node.js/npm packages
if which -s npm && [ -f package.json ]; then
  echo "* Installing npm packages..."
  npm install
fi

echo "Done"
exit 0
