#!/bin/sh
#
# Usage: pull
#
# Pulls remote changes using rebase & tries to rebundle,
# safely stashing and re-applying your local changes, if any
#

remote="origin"
branch=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')

stash=$(git stash)

git fetch --all || exit 1
git pull --rebase $remote $branch || exit 1

if [[ "$stash" =~ "No local changes to save" ]]; then
  echo "* No stashed changes, not popping"
else
  echo "* Popping stash..."
  git stash pop
fi

if which -s bundle; then
  bundle check || bundle install
fi

echo "Done"
