#!/bin/bash
#
# Usage: stash [options]
#
# Stashes all changes (including untracked), or run git stash will all arguments
#

# Abort if this isn't a git repository
git rev-parse --is-inside-work-tree >/dev/null || exit $?

# If ran without arguments, stall all files, including untracked
if [ -z "$1" ]; then
	echo "🐿️  Stashing changes..."
	git stash --include-untracked
	exit 0
fi

# Otherwise pass all arguments to git stash
git stash "$@"
